---

# NOTE we may need to install packages or whatever

# NOTE we may need to activate linux forwarding

- name: write iptables routing config
  tags: iptables
  template:
    src: iptables.rules.j2
    dest: /etc/iptables.rules
  notify: reload iptables
...
