---
# file: site.yml
#
#   for ansible 2.2 (as packaged for Debian 9)
#
#   for my home network with ~2 physical servers and ~8 qemu-kvm machines


#  I want some maintenance for my Debian systems:

- hosts: debian9
  become: true
  roles:
    - debian-9-system

#  I use dnsmasq for DHCP, TFTP and DNS:

- hosts: dnsmasq_servers
  become: true
  roles:
    - dnsmasq-servers

#  I use unbound for DNS:

- hosts: unbound_servers
  become: true
  roles:
    - unbound-servers

#  I have a number of headless virtual machines

- hosts: headless_vms
  become: true
  roles:
    - ttyS0-servers
    - powerbutton-listeners
...
