---
# file: site.yml
#
#   for ansible 2.2 (as packaged for Debian 9)
#
#   for my home network with ~2 physical servers and ~8 qemu-kvm machines

#  I want some maintenance for my Debian systems:

- hosts: all
  tasks:
     - name: Group by distribution and release
       group_by:
         key: os_{{ ansible_distribution }}_{{ ansible_distribution_release }}

- hosts: os_Debian_stretch
  become: true
  roles:
    - debian-9-system

#  I use dnsmasq for DHCP, TFTP and DNS:

- hosts: dnsmasq_servers
  become: true
  roles:
    - dnsmasq-server

# I have an NFS server

- hosts: nfs_servers
  become: true
  roles:
    - nfs-server

#  I have some NAT router

- hosts: nat_routers
  become: true
  roles:
    - nat-router

#  I use unbound for DNS:

- hosts: unbound_servers
  become: true
  roles:
    - unbound-server

#  I have a number of headless virtual machines

- hosts: headless_vms
  become: true
  roles:
    - ttyS0-server
    - powerbutton-listener

#  I have some apache 2 servers

- hosts: apache2_servers
  become: true
  roles:
    - apache2-server

#  I have one(?) certbot client

- hosts: certbot_apache_clients
  roles:
    - certbot-apache-client

#  I have some smtp servers

- hosts: smtp_servers
  roles:
    - smtp-server

#  I have some smtp satellite systems

- hosts: smtp_satellites
  become: true
  roles:
    - smtp-satellite
...
