---
# file: site.yml

- hosts: testing
  remote_user: testuser
  become: true
  tasks:
    - name: just ping
      ping:

- hosts: testing
  remote_user: testuser
  become: true
  tasks:
    - name: echo hosts
      command: echo {{ item.host }}
      with_items: "{{ network_mappings['localnet'].hosts }}"

...
