---
# file: virt-guests.yml
#
# status: under development
#
# inspired by https://github.com/sfromm/ansible-playbooks/


- hosts: libvirt_servers
  remote_user: ansible-agent
  become: true

  vars:

    - installer_location:
        debian9: "http://httpredir.debian.org/debian/dists/stretch/main/installer-amd64/"

    - vms:

        - vm_name: ansible-client
          hostname: ansible-client
          libvirt_host: wollishofen.localnet
          ram_in_MB: 1024
          vcpus: 1
          os_type: linux
          os_variant: debian9
          mac: 52:54:00:03:92:16
          volumes:
            - name: ansible-client.qcow2
              size_in_MB: 2048
              pool: qcow

        - vm_name: vm-another-test
          hostname: another-test
          libvirt_host: wollishofen.localnet
          ram_in_MB: 1024
          vcpus: 1
          os_type: linux
          os_variant: debian9
          mac: 52:54:00:2a:5c:f8
          volumes:
            - name: vm-another-test.qcow2
              size_in_MB: 2048
              pool: qcow
            - name: vm-another-test-swap.qcow2
              size_in_MB: 512
              pool: qcow-transient

  tasks:

    - name: ensure libvirt and python tools are installed
      package: name="{{ item }}" state=present
      with_items:
        - python-libvirt
        - python-lxml

    - name: ensure libvirt daemon is running
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: get list of virtual networks
      virt_net: command=facts
      register: virt_net_facts

    # TODO: define missing nets

    # TODO: check and fix net modifications

    - name: get list of volume pools and volumes
      virt_pool: command=facts
      register: virt_pool_facts

    # TODO: define missing pools

    # TODO: check and fix pool modifications

    - name: get list of vms
      virt: command=list_vms
      register: virt_vms

    - name: create missing volumes
      command: virsh vol-create-as "{{ item.1.pool }}" "{{ item.1.name }}" "{{ item.1.size_in_MB }}"M --format qcow2
      with_subelements:
        - "{{ vms }}"
        - volumes
      when: (inventory_hostname == item.0.libvirt_host) and (item.1.name not in virt_pool_facts.ansible_facts.ansible_libvirt_pools[item.1.pool].volumes)

    - name: update list of volume pools and volumes
      virt_pool: command=facts
      register: virt_pool_facts

    - name: report error on missing volumes
      fail: "It seems that host {{ item.0.libvirt_host }} pool {{ item.1.pool }} volume {{ item.1.name}} is missing"
      with_subelements:
        - "{{ vms }}"
        - volumes
      when: (inventory_hostname == item.0.libvirt_host) and (item.1.name not in virt_pool_facts.ansible_facts.ansible_libvirt_pools[item.1.pool].volumes)

    - name: create missing vms
      command: echo virt-install
               --virt-type kvm
               -n "{{ item.vm_name }}"
               -r "{{ item.ram_in_MB }}"
               --vcpus="{{ item.vcpus }}"
               --cpu qemu64,-svm
               -l "{{ installer_location[item.os_variant] }}"
               --initrd-inject=preseed.cfg \
               --disk vol="{{ item.volumes[0].pool }}/{{ item.volumes[0].name }},bus=virtio"
               -w network=localnet7,mac="{{ item.mac }}",model=virtio \
               --os-type "{{ item.os_type }}" \
               --os-variant "{{ item.os_variant }}"
               --controller usb,model=none
               --graphics none
               --extra-args "auto=true hostname={{ item.hostname }} console=ttyS0"
               --noautoconsole
      with_items:
        - "{{ vms }}"
      when: (inventory_hostname == item.libvirt_host) and (item.vm_name not in virt_vms)

    - command: echo Hallo
      with_items:
        - host: wollishofen.localnet
      when: inventory_hostname == "{{ item.host }}"
...
