---
# file: virt-guests.yml
#
# status: under development
#
# inspired by https://github.com/sfromm/ansible-playbooks/


- hosts: libvirt_servers
  remote_user: ansible-agent
  become: true

  vars:

    - vms:

        - name: ansible-master
          host: wollishofen.localnet
          volumes:
            - name: ansible-master.qcow2
              size_in_MB: 2048
              pool: qcow

        - name: vm-another-test
          host: wollishofen.localnet
          volumes:
            - name: vm-another-test.qcow2
              size_in_MB: 2048
              pool: qcow
            - name: vm-another-test-swap.qcow2
              size_in_MB: 512
              pool: qcow-transient

  tasks:

    - name: ensure libvirt and python tools are installed
      package: name=python-libvirt state=present
      with_items:
        - python-libvirt
        - python-lxml

    - name: ensure libvirt daemon is running
      service:
        name: libvirtd
        state: started
        enabled: yes

    - name: get list of virtual networks
      virt_net: command=facts
      register: virt_net_facts

    # TODO: define missing nets

    # TODO: check and fix net modifications

    - name: get list of image pools
      virt_pool: command=facts
      register: virt_pool_facts

    # TODO: define missing pools

    # TODO: check and fix pool modifications

    - name: get list of vms
      virt: command=list_vms
      register: virt_vms

    - name: create missing volumes
      command: virsh vol-create-as "{{ item.1.pool }}" "{{ item.1.name }}" "{{ item.1.size_in_MB }}"M --format qcow2
      with_subelements:
        - "{{ vms }}"
        - volumes
      when: (inventory_hostname == item.0.host) and (item.1.name not in virt_pool_facts.ansible_facts.ansible_libvirt_pools[item.1.pool].volumes)

    # TODO: cross check: all required volumes exist

    # TODO: create missing vms

    - command: echo Hallo
      with_items:
        - host: wollishofen.localnet
      when: inventory_hostname == "{{ item.host }}"
...
