---
- name: update package index
  apt: update_cache=yes
  tags:
    - packages-update

- name: upgrade packages
  apt: upgrade=yes
  tags:
    - packages-update

- name: remove unreferenced packages
  command: apt-get autoremove -y
  tags:
    - packages-update
    - packages-update-cleanup

- name: cleanup diskspace
  command: apt-get clean
  tags:
    - packages-update
    - packages-update-cleanup
...
