---
- name: Have packages for powerbutton shutdown support
  package:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"
  with_items:
    - dbus
    - libpam-systemd
...
