---

- name: have MySQL or similar installed
  package:
    name: default-mysql-server
    state: present

- name: have MySQL service running
  service:
    name: mysql
    enabled: yes
    state: started
...
