---
- name: enable debconf-get-selections
  package:
    name: debconf-utils
    state: present
  tags:
    - smtp-satellite

- name: adjust postfix installation settings
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { name: "postfix", question: "postfix/mailname",         vtype: "string", value: "{{ ansible_fqdn }}" }
    - { name: "postfix", question: "postfix/main_mailer_type", vtype: "select", value: "Satellite system" }
    - { name: "postfix", question: "postfix/relayhost",        vtype: "string", value: "{{ smtp_relay_host }}" }
  tags:
    - smtp-satellite

- name: enable postfix
  package:
    name: postfix
    state: present
  tags:
    - smtp-satellite
...
