---

- name: "dnsmasq: Essential configuration lines"
  lineinfile:
    dest: "{{ dnsmasq_config_file }}"
    line: "{{ item.line }}"
    state: present
  notify: restart dnsmasq
  with_items:
    - comment: "Never forward plain names (without a dot or domain part)"
      line: "domain-needed"
    - comment: "Never forward addresses in the non-routed address spaces."
      line: "bogus-priv"
    - comment: "Never bind to wildcard address."
      line: "bind-interfaces"

- name: "dnsmasq: Interfaces"
  lineinfile:
    dest: "{{ dnsmasq_config_file }}"
    line: "interface={{ item }}"
    state: present
  notify: restart dnsmasq
  with_items:
    - "{{ dnsmasq_confs[this_host_label].interfaces }}"
...
