---

- name: "cleanup: remove redundant static hosts from main config"
  lineinfile:
    dest: "{{ dnsmasq_config_file }}"
    regexp: "(?i)^dhcp-host=({{ item.mac }}|[0-9a-f:]+,{{ item.host }}|[0-9a-f:]+,[a-zA-Z0-9-]+,{{ item.ip }}),"
    state: absent
  with_items: "{{ network_mappings['localnet'].hosts }}"
  notify: restart dnsmasq


- name: enlist static hosts and IPs in DHCP/DNS configuration
  template:
    src: dnsmasq.dhcp-hosts.conf.j2
    dest: "{{ dnsmasq_dhcp_hosts_config }}"
  notify: restart dnsmasq

- name: include static host config in main config
  lineinfile:
    dest: "{{ dnsmasq_config_file }}"
    line: "conf-file={{ dnsmasq_dhcp_hosts_config }}"
    state: present
  notify: restart dnsmasq
...
