---
# inspired by https://github.com/sfromm/ansible-playbooks/

- include: task_install_tools.yml
- include: task_determine_vms_to_install.yml
- include: task_provide_networks.yml
- include: task_provide_pools_and_volumes.yml
- include: task_install_missing_vms.yml

# TODO? now the installation runs, and eventually finishes or fails. how do we know?

# TODO switch ansible agent from password to ssh key

# TODO prepare swap partition

# TODO include swap partition

...
