---
- name: get list of volume pools and volumes
  virt_pool: command=facts
  register: virt_pool_facts

# TODO: define missing pools

# TODO: check and fix pool modifications

- name: create missing volumes
  command: virsh vol-create-as "{{ item.1.pool }}" "{{ item.1.name }}" "{{ item.1.size_in_MB }}"M --format qcow2
  with_subelements:
    - "{{ vm_definitions_presence.results | json_query('[?skipped].item') }}"
    - volumes
  when: item.1.name not in virt_pool_facts.ansible_facts.ansible_libvirt_pools[item.1.pool].volumes

- name: update list of volume pools and volumes
  virt_pool: command=facts
  register: virt_pool_facts

- name: report error on missing volumes
  fail: "It seems that host {{ this_host_label }} pool {{ item.1.pool }} volume {{ item.1.name}} is missing"
  with_subelements:
    - "{{ vm_definitions_presence.results | json_query('[?skipped].item') }}"
    - volumes
  when: item.1.name not in virt_pool_facts.ansible_facts.ansible_libvirt_pools[item.1.pool].volumes
...
