---

# NOTE we may need to install packages or whatever

- name: enable IPv4 forwarding
  tags: iptables
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes

- name: write iptables routing config
  tags: iptables
  template:
    src: iptables.rules.j2
    dest: /etc/iptables.rules
  notify: reload iptables
...
